spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/decision_board
spring.datasource.username=decision_board
spring.datasource.password=decision_board

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true